version: '3'

services:
  web:
    restart: always
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    # volumes:
    #   - ./:/code:ro
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=price_db
    expose:
      - 5432

volumes:
  postgres_data:
