"""Rename and fix InfoResource fields

Revision ID: d5d55eae195a
Revises: 67c328bae333
Create Date: 2024-08-04 11:18:24.761014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d55eae195a'
down_revision: Union[str, None] = '67c328bae333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('url', sa.String(), nullable=False))
    op.alter_column('sources', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sources', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('sources', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('sources', 'url')
    # ### end Alembic commands ###
